### ISSUE TITLE
Any LDAP Host configuration fails

### ISSUE THREAD

**Issue by scheibj** [ShMaunder/JMapMyLDAP#13]
I have the same problem as felly had 2 months ago.

> Warning
> Invalid field: Name

I have a Windows 2008 R2 64 bit server with IIS7. It works correctly with xampp server on the same machine, but I can not make it work under IIS. I printed out the LDAP Host Configuration page and a phpinfo() page also into PDF. I can share them if it helps.
I just wondering what could be the problem?

thanks,
scheibj

**Comment by ShMaunder** [comment]
I've had several reports of the regex failing to work with some characters on Windows web servers. I only test against Linux based web servers where I can easily automate testing.

Currently the regex in `/libraries/shmanic/form/rules/ldapdomain.php` is failing and in another reported case `/libraries/shmanic/user/adapter/ldap.php` where it validates the domain.

This regex must be changed to match that of the Joomla username anyway due to the new domain implementation in 2.1. I'll create a branch using the same as the Joomla username which is supported on IIS:
`preg_match('#[<>"\'%;()&\\\\]|\\.\\./#', $str) || strlen(utf8_decode($str)) < 2 || trim($str) != $str`

I'll post with the branch and file for you to test when its done.

**Comment by ShMaunder** [comment]
Had confirmation from another instance of this problem that the code change in the commit solves the problem. Pushed to 2.0.x.

**Comment by Nacho223** [comment]
Hello, I have the exact same problem. Same Windows Server system, and Joomla 3.3.1. 

How did you solve this?

Many thanks

**Comment by scheibj** [comment]
Hello,

Forget MS IIS as the webserver!

I installed XAMPP for Windows (Apache webserver) and it works.

scheibj

**Comment by Nacho223** [comment]
I have a windows server up and running in production giving service to nearly 30 webs, ADDS and I really need this OS and webserver, so I'm not migrating to a linux machine or apache. I really need help on this.

**Comment by Nacho223** [comment]
Please?

**Comment by ShMaunder** [comment]
I'm currently tied up with other things at the moment (away from project)... but I built the package with this fix included some weeks back at http://server.shmanic.co.uk/jmml_builds/2.0.2.2/packages/ <-- I have no idea how well this works as it is not a "stable release".

**Comment by Nacho223** [comment]
Thank you very much!!!! I'l try it.

**Comment by ShMaunder** [comment]
Apologies this took so long to get to stable. 2.0.2.2 is now published as stable with this issue fixed.

**Comment by dtrencevski** [comment]
Fixed by going to C:\xampp\htdocs\YourJoomlaSite\libraries\shmanic\form\rules and edit the ldapdomain.php file. Replace [A-Z0-9_.-\s] with ^[^<>"\'%;()&\\
